# Generated by Django 3.1.2 on 2020-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.CharField(max_length=280),
        ),
    ]
